#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "Error: this bootstrap script currently supports macOS only."
  exit 1
fi

configure_homebrew() {
  if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
}

configure_homebrew
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  configure_homebrew
fi

if ! command -v go >/dev/null 2>&1; then
  echo "Installing Go..."
  brew install go
fi

if [[ ! -f .env ]]; then
  if command -v openssl >/dev/null 2>&1; then
    JWT_SECRET_VALUE="$(openssl rand -hex 32)"
  else
    JWT_SECRET_VALUE="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)"
  fi
  umask 077
  {
    echo "# Generated by start.sh for local development."
    echo "PORT=8000"
    echo "JWT_SECRET=$JWT_SECRET_VALUE"
    echo "HK_INSURANCE_RAG_ENABLED=true"
    echo "HK_INSURANCE_RAG_DATA_PATH=assets/rag/hk_insurance"
    echo "HK_INSURANCE_RAG_EMBEDDING_ENABLED=false"
    echo "CHAT_RAG_RUNTIME=go"
    echo "SHOP_CHECKOUT_ENABLED=false"
    echo "USE_MOCK_SHOPIFY=true"
    echo "HICUSTOM_ENABLED=false"
    echo "USE_MOCK_HICUSTOM=true"
    echo "DEV_EXPOSE_VERIFICATION_CODES=true"
    echo "SEED_TEST_ACCOUNTS=true"
  } > .env
  echo "Created local .env with a random JWT secret."
else
  echo "Using existing .env (left unchanged)."
fi

if command -v lsof >/dev/null 2>&1 && lsof -nP -iTCP:8000 -sTCP:LISTEN >/dev/null 2>&1; then
  echo "Error: port 8000 is already in use. Stop that process and run this script again."
  exit 1
fi

echo "Downloading Go modules..."
go mod download

echo "Starting Pawrd Backend at http://localhost:8000"
exec go run ./cmd/server
